name: Follow for Follow
on:
  schedule:
    - cron: "59 14 * * *" # every day at 9:59 AM EST
    - cron: "0 */6 * * *" # * * * * * <- min hour day month dayOfWeek then your cmd (this is every 6 hours so 0000, 0600, 1200, 1800 UTC)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: go run followforfollow.go
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
