name: Follow for Follow
on:
  push:
    branches:
      - main
  schedule:
<<<<<<< HEAD
    - cron: "* 4 * * *"
||||||| parent of dfc659f (Change cron schedule from 15 to 20 minutes)
    - cron: "15 * * * *"
=======
    - cron: "20 * * * *"
>>>>>>> dfc659f (Change cron schedule from 15 to 20 minutes)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: go run followforfollow.go
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
